### ISSUE TITLE
WFN.exe won't start.

### ISSUE THREAD

**Issue by Rebask** [wokhansoft/WFN#19]
I get an error box saying 'The type initializer for 'Wokhan.WindowsFirewallNotifier.Common.Helpers.LogHelper' threw an exception.' Closing it gives me a 'has stopped working' box.

It had been working fine until I ran DisableWFN.cmd to deal with another issue I was having, and I tried to start it again afterwords.

**Comment by AtlasHackert** [comment]
What folder are you running WFN from? Do you have "writing permission" in that folder, i.e. can you save files to it?

**Comment by Rebask** [comment]
It was in a folder off of a non C: drive where it working fine until I ran DisableWFN.cmd, other than an unrelated bug involving notifier.exe spam. When it wouldn't launch I also tried a folder on the root of my C: drive, with no luck.

I have ownership and full control of these folders.

**Comment by AtlasHackert** [comment]
Can you post a copy of the entry of the crash as it appears in Windows' Event Viewer? (It should be in the "Application" folder.)

**Comment by Rebask** [comment]
Application: WFN.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Xml.XmlException
   at System.Xml.XmlTextReaderImpl.Throw(System.Exception)
   at System.Xml.XmlTextReaderImpl.Throw(System.String, System.String[])
   at System.Xml.XmlTextReaderImpl.ParseText(Int32 ByRef, Int32 ByRef, Int32 ByRef)
   at System.Xml.XmlTextReaderImpl.ParseText()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlTextReader.Read()
   at System.Xml.XmlTextReaderImpl.Skip()
   at System.Xml.XmlTextReader.Skip()
   at System.Configuration.XmlUtil.StrictSkipToNextElement(System.Configuration.ExceptionAction)
   at System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(System.Configuration.XmlUtil, System.String, Boolean, System.String, System.Configuration.OverrideModeSetting, Boolean)
   at System.Configuration.BaseConfigurationRecord.ScanSections(System.Configuration.XmlUtil)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()

Exception Info: System.Configuration.ConfigurationErrorsException
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(System.Configuration.ConfigurationSchemaErrors)
   at System.Configuration.Configuration..ctor(System.String, System.Type, System.Object[])
   at System.Configuration.ClientConfigurationHost.OpenExeConfiguration(System.Configuration.ConfigurationFileMap, Boolean, System.Configuration.ConfigurationUserLevel, System.String)
   at System.Configuration.ConfigurationManager.OpenExeConfigurationImpl(System.Configuration.ConfigurationFileMap, Boolean, System.Configuration.ConfigurationUserLevel, System.String, Boolean)
   at Wokhan.WindowsFirewallNotifier.Common.Helpers.CustomSettingsProvider.GetUserSettings(Boolean)
   at Wokhan.WindowsFirewallNotifier.Common.Helpers.CustomSettingsProvider.GetPropertyValues(System.Configuration.SettingsContext, System.Configuration.SettingsPropertyCollection)
   at System.Configuration.SettingsBase.GetPropertiesFromProvider(System.Configuration.SettingsProvider)
   at System.Configuration.SettingsBase.GetPropertyValueByName(System.String)
   at System.Configuration.SettingsBase.get_Item(System.String)
   at System.Configuration.ApplicationSettingsBase.GetPropertyValue(System.String)
   at System.Configuration.ApplicationSettingsBase.get_Item(System.String)
   at Wokhan.WindowsFirewallNotifier.Common.Settings.get_FirstRun()
   at Wokhan.WindowsFirewallNotifier.Common.Helpers.LogHelper..cctor()

Exception Info: System.TypeInitializationException
   at Wokhan.WindowsFirewallNotifier.Common.Helpers.LogHelper.Debug(System.String)
   at Wokhan.WindowsFirewallNotifier.Console.App..ctor()
   at Wokhan.WindowsFirewallNotifier.Console.App.Main()

**Comment by AtlasHackert** [comment]
Hmm, something somehow got messed up in the configuration files...

Can you send me a copy of the following folders:
C:\Users\<user>\AppData\Roaming\Wokhan Solutions\WFN
C:\Users\<user>\AppData\Local\Wokhan Solutions\WFN
for both your own user account, and the administrator account? (There is no identifying information stored in the files in these folders.)

**Comment by Rebask** [comment]
[user.config_roaming.txt](https://github.com/wokhansoft/WFN/files/1341468/user.config_roaming.txt)
[user.config_local.txt](https://github.com/wokhansoft/WFN/files/1341472/user.config_local.txt)
There is no separate user account. Not sure why it's set up this way, this is a windows 10 machine that upgraded from windows 7.

**Comment by AtlasHackert** [comment]
I think something went wrong with uploading user.config_local.txt... It appears cut-off?

**Comment by Rebask** [comment]
That mess of NUL is how the original is too.

**Comment by AtlasHackert** [comment]
That can't be good. :|
Can you delete that configuration file, and try again? I have no clue how it got corrupted. We are using the XML file writing of the .NET framework, so this is also not something we can fix if it's a bug.

**Comment by Rebask** [comment]
Could it be caused by trying to write during a hard reset? That other bug I mentioned has forced me to do a couple in the last few days. Is the infinite Notifier.exe thing a known issue, or should I create a new entry for it?

I deleted both configs and it now starts fine. Woo!

**Comment by AtlasHackert** [comment]
Glad you got it working again!

Yes, a hard reboot could cause this. These NULLs can happen if the writing of a file is interrupted in a bad way.

And the infinite Notifier.exe is indeed a know issue. There's no good fix (it's a limitation of WFN's design), and I haven't found a good mitigation yet. :(
